"""V32.M1.1.X-followup — turn_graph budget guard.

Without this guard the LLM occasionally drifts past the framework's
planned `sum(question_budget)`. Observed in production:
  progress reads 5/5,
  AI 场景洞察 reads 5/5,
  but the interviewer asks question 7 anyway.

`_total_question_budget` derives the cap from the framework JSON
that was generated by FrameworkAgent at session creation. The
`next_question_node` in turn_graph then forces `should_end=true`
once `(turn_index + 1) >= budget`, so the desktop statechart
transitions to `ended` instead of accepting another turn.

These tests exercise the helper directly. Wiring the override into
`next_question_node` is covered by the existing `test_graph_contract.py`
plus an integration test elsewhere.
"""

from __future__ import annotations

import json

from app.orchestrator.turn_graph import _total_question_budget


def test_total_budget_sums_stage_budgets() -> None:
    framework = {
        "stages": [
            {"name": "暖场", "question_budget": 1},
            {"name": "深挖", "question_budget": 3},
            {"name": "反问", "question_budget": 1},
        ],
    }
    assert _total_question_budget(json.dumps(framework)) == 5


def test_total_budget_returns_none_for_malformed_json() -> None:
    assert _total_question_budget("{not json") is None


def test_total_budget_returns_none_when_stages_missing() -> None:
    assert _total_question_budget(json.dumps({})) is None


def test_total_budget_returns_none_for_empty_stages() -> None:
    assert _total_question_budget(json.dumps({"stages": []})) is None


def test_total_budget_skips_non_int_budgets() -> None:
    framework = {
        "stages": [
            {"name": "ok", "question_budget": 2},
            {"name": "bad-type", "question_budget": "three"},
            {"name": "missing"},
            {"name": "negative", "question_budget": -1},
            {"name": "zero", "question_budget": 0},
        ],
    }
    # Only the first row counts — non-ints, missing keys, and
    # non-positive values are ignored. The helper still returns the
    # surviving sum so the guard kicks in based on partial data
    # instead of going silent.
    assert _total_question_budget(json.dumps(framework)) == 2


def test_total_budget_returns_none_when_all_budgets_invalid() -> None:
    framework = {
        "stages": [
            {"name": "a", "question_budget": "x"},
            {"name": "b", "question_budget": -2},
        ],
    }
    # No surviving budget → fall through to the LLM's own should_end.
    assert _total_question_budget(json.dumps(framework)) is None


def test_total_budget_handles_non_dict_input() -> None:
    assert _total_question_budget(json.dumps([1, 2, 3])) is None
