"""V32.M1.1.X-followup — turn_graph budget guard.

Without this guard the LLM occasionally drifts past the framework's
planned `sum(question_budget)`. Observed in production:
  progress reads 5/5,
  AI 场景洞察 reads 5/5,
  but the interviewer asks question 7 anyway.

`_total_question_budget` derives the cap from the framework JSON
that was generated by FrameworkAgent at session creation. The
`next_question_node` in turn_graph then forces `should_end=true`
once `(turn_index + 1) >= budget`, so the desktop statechart
transitions to `ended` instead of accepting another turn.

These tests exercise the helper directly. Wiring the override into
`next_question_node` is covered by the existing `test_graph_contract.py`
plus an integration test elsewhere.
"""

from __future__ import annotations

import json

from app.orchestrator.turn_graph import _total_question_budget


def test_total_budget_sums_stage_budgets() -> None:
    framework = {
        "stages": [
            {"name": "暖场", "question_budget": 1},
            {"name": "深挖", "question_budget": 3},
            {"name": "反问", "question_budget": 1},
        ],
    }
    assert _total_question_budget(json.dumps(framework)) == 5


def test_total_budget_returns_none_for_malformed_json() -> None:
    assert _total_question_budget("{not json") is None


def test_total_budget_returns_none_when_stages_missing() -> None:
    assert _total_question_budget(json.dumps({})) is None


def test_total_budget_returns_none_for_empty_stages() -> None:
    assert _total_question_budget(json.dumps({"stages": []})) is None


def test_total_budget_skips_non_int_budgets() -> None:
    framework = {
        "stages": [
            {"name": "ok", "question_budget": 2},
            {"name": "bad-type", "question_budget": "three"},
            {"name": "missing"},
            {"name": "negative", "question_budget": -1},
            {"name": "zero", "question_budget": 0},
        ],
    }
    # Only the first row counts — non-ints, missing keys, and
    # non-positive values are ignored. The helper still returns the
    # surviving sum so the guard kicks in based on partial data
    # instead of going silent.
    assert _total_question_budget(json.dumps(framework)) == 2


def test_total_budget_returns_none_when_all_budgets_invalid() -> None:
    framework = {
        "stages": [
            {"name": "a", "question_budget": "x"},
            {"name": "b", "question_budget": -2},
        ],
    }
    # No surviving budget → fall through to the LLM's own should_end.
    assert _total_question_budget(json.dumps(framework)) is None


def test_total_budget_handles_non_dict_input() -> None:
    assert _total_question_budget(json.dumps([1, 2, 3])) is None


def test_total_budget_supports_agent_pace_plan_shape() -> None:
    # FrameworkAgentOutput shape — what `_load_framework_json` actually
    # returns when the WS endpoint serialises the agent payload (so
    # the Interviewer Agent keeps `predicted_questions` in scope).
    # `_agent_to_legacy_framework` converts via max(1, rough_minutes // 3).
    framework = {
        "pace_plan": {
            "total_minutes": 30,
            "segments": [
                {"name": "暖场", "rough_minutes": 4, "goal": "..."},
                {"name": "项目深挖", "rough_minutes": 12, "goal": "..."},
                {"name": "能力追问", "rough_minutes": 9, "goal": "..."},
                {"name": "反问", "rough_minutes": 5, "goal": "..."},
            ],
        },
        "predicted_questions": None,
    }
    # 4//3=1, 12//3=4, 9//3=3, 5//3=1 → 1+4+3+1 = 9
    assert _total_question_budget(json.dumps(framework)) == 9


def test_total_budget_pace_plan_floors_at_one_per_segment() -> None:
    # rough_minutes < 3 should still contribute 1 (max(1, ...)).
    framework = {
        "pace_plan": {
            "total_minutes": 5,
            "segments": [
                {"name": "a", "rough_minutes": 1, "goal": "..."},
                {"name": "b", "rough_minutes": 2, "goal": "..."},
                {"name": "c", "rough_minutes": 6, "goal": "..."},
            ],
        },
    }
    # 1+1+2 = 4
    assert _total_question_budget(json.dumps(framework)) == 4


def test_total_budget_legacy_stages_take_precedence_over_pace_plan() -> None:
    # If both shapes are present (defensive), explicit stages win
    # because they're the canonical legacy contract.
    framework = {
        "stages": [
            {"name": "stage", "question_budget": 6},
        ],
        "pace_plan": {
            "total_minutes": 90,
            "segments": [
                {"name": "x", "rough_minutes": 30, "goal": "..."},
            ],
        },
    }
    assert _total_question_budget(json.dumps(framework)) == 6


def test_total_budget_returns_none_when_pace_plan_segments_invalid() -> None:
    framework = {
        "pace_plan": {
            "total_minutes": 30,
            "segments": [
                {"name": "bad", "rough_minutes": "twelve"},
                {"name": "missing"},
                {"name": "neg", "rough_minutes": -5},
            ],
        },
    }
    assert _total_question_budget(json.dumps(framework)) is None
